### ISSUE TITLE
test

### ISSUE THREAD

**Issue by martinheidegger** [owddm/organization#1]
@coliff hello (sorry to disturb, need it to show something off)

**Comment by coliff** [comment]
:-)  How are you doing? Hope all is good. Sorry I disappeared off the radar for a while. My parents visited Japan for the first time for a few weeks and was busy showing them around... so wasn't able to work on the OWDDM website at all... and then at the last minute I was unable to join the last meetup as had to look after our little boy. I'm going to properly start working on site soon - and really looking forward to seeing you and everyone else at the next meetup.

**Comment by martinheidegger** [comment]
If people suddenly loose contact I assume that they are busy! Thank you for not forgetting about OWDDM. Actually Naomi is eager to work on the site as well and would love to have some guidance! In any case: I am curious about the things to come!
